---

- hosts: localhost

  vars:
    - create_user_file: yes
    - user: ansadmin

  tasks:
    - name: create file for user
      file:
        path: /home/{{user}}/file1
        state: touch
      when: create_user_file
