---
- name: firstplaybook
  hosts: localhost
  become: yes
  become_user: root

  tasks:
    - name: Install Apache httpd
      yum:
       name: httpd
       state: present

    - name: Second task
      service:
       name: httpd
       state: started
